{
 "title": "Battery vs House consumption",
 "time": { "from": "2023-01-05T09:01:20.365Z", "to": "2023-01-05T21:42:43.787Z" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cifras",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT tunix as time, battery_soc as Carga_batería, pbattery1 as Batería,  house_consumption as Consumo, ppv as FV, pgrid as Red from inverter_log;\n\n ",
     "rawQueryText": "SELECT tunix as time, battery_soc as Carga_batería, pbattery1 as Batería,  house_consumption as Consumo, ppv as FV, pgrid as Red from inverter_log;\n\n ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "FV+Battery vs consumo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "queryText": "SELECT tunix as time ,house_consumption as Consumo, ppv as FV, pbattery1 as Batería, pgrid as Red from inverter_log;",
     "rawQueryText": "SELECT tunix as time ,house_consumption as Consumo, ppv as FV, pbattery1 as Batería, pgrid as Red from inverter_log;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Fotovoltaica 1 vs 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "queryText": "SELECT tunix as time ,ppv1, ppv2, ppv from inverter_log;",
     "rawQueryText": "SELECT tunix as time ,ppv1, ppv2, ppv from inverter_log;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "queryText": "SELECT unixepoch(t) as time ,battery_soc from inverter_log;\n",
     "rawQueryText": "SELECT unixepoch(t) as time ,battery_soc from inverter_log;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperaturas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "queryText": "SELECT tunix as time ,battery_temperature as Bateria_temp, temperature as Inversor_temp from inverter_log;",
     "rawQueryText": "SELECT tunix as time ,battery_temperature as Bateria_temp, temperature as Inversor_temp from inverter_log;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}